Recompose
wolox-training/ssc-react pull request #22
Opened 2019-08-29 16:44 UTC by SaraIsabelSantacruz

## Summary
- createTypes and completeTypes added
-actionsCreators changed like redux-recompose suggests
-createReducer, completeReducer and completeState added
-reducers changed like redux-recompose suggests
-fetchMiddleware added

## Trello Card
https://trello.com/c/jw1x90Qv

2019-08-30 18:50 UTC, gon-escalante commented on react/tic-tac-toe-api/index.js
> +const router = jsonServer.router('db.json');
remove this space

2019-08-30 18:50 UTC, gon-escalante commented on react/tic-tac-toe/src/redux/data/actions.js
> +export const actions = createTypes(completeTypes(['GET_DATA', 'CREATE_DATA', 'ON_LOGIN', 'SET_AUTH']), '@@SOCCER');
`ON_LOGIN` and `SET_AUTH` dont belong here

2019-08-30 18:50 UTC, gon-escalante commented on react/tic-tac-toe/src/redux/data/reducers.js
> +  primaryActions: [actions.GET_DATA, actions.CREATE_DATA, actions.ON_LOGIN]
`ON_LOGIN` doesnt belong here

2019-08-30 18:50 UTC, gon-escalante commented on react/tic-tac-toe/src/redux/login/actions.js
> +export const actions = createTypes(completeTypes(['ON_LOGIN', 'SET_AUTH', 'ON_LOGOUT']), '@@SOCCER');
i dont think `SET_AUTH` and `ON_LOGOUT` need the complete types, remember that `completeTypes` creates the actions `SET_AUTH_FAILURE` and `SET_AUTH_SUCCESS` to handle the loading state, and set auth and loading dont seem to need a loading state.

2019-08-30 19:03 UTC, CrisVega08 requested changes
Great work with redux-recompose

2019-08-30 19:03 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/login/actions.js
> +    target: 'setToken',
Use a constant for targets

2019-08-30 19:03 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/login/actions.js
> +    target: 'isUserLoggedin'
Same

2019-08-30 19:03 UTC, CrisVega08 commented on react/tic-tac-toe/src/redux/login/actions.js
> +    target: 'isUserLoggedin'
Same

2019-09-02 14:39 UTC, gon-escalante approved these changes
nice work 👏

2019-09-27 20:16 UTC, merged